### ISSUE TITLE
[Forge and Fabric 1.18.2 - 1.20] Angel block gets consumed when above or below build limit

### ISSUE THREAD

**Issue by Christofmeg** [LaidBackSloth/AngelBlockRenewed#5]
Minecraft: 1.19.2
Modloader: Forge 43.2.14
Angel Block Renewd: 1.0

When a player tries to place angel block above or below build limit the ItemStack shrinks when it should not.

Tested dimension: minecraft:the_end

**Comment by LaidBackSloth** [comment]
Thanks for reporting and solving the issue
